# Generated by Django 4.1.13 on 2025-04-28 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="blog_post_publish_493ec4_idx",
        ),
    ]
