# Generated by Django 4.1.13 on 2025-04-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_post_blog_post_publish_493ec4_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="published"),
        ),
    ]
